export const config = {
  DROPBOX_CLIENT_ID: process.env.REACT_APP_CLIENT_ID,
  DROPBOX_CLIENT_SECRET: process.env.REACT_APP_CLIENT_SECRET,
  DROPBOX_REDIRECT_URI: process.env.REACT_APP_REDIRECT_URI,
};
